/**********************************************************************************************************************************************\
	Copyright(C) 1993-1996 Id Software, Inc.
	Copyright(C) 2005-2014 Simon Howard

	This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

	DESCRIPTION:
		Event handling.
		Events are asynchronous inputs generally generated by the game user. Events can be discarded if no responder claims them
\**********************************************************************************************************************************************/

#include "d_event.h"

constexpr size_t MAXEVENTS{64};

static EventType events[MAXEVENTS];
static int eventhead;
static int eventtail;

// Called by the I/O functions when input is detected
void D_PostEvent(EventType* ev)
{
	events[eventhead] = *ev;
	eventhead = (eventhead + 1) % MAXEVENTS;
}

// Read an event from the queue.
EventType* D_PopEvent()
{
	EventType* result;

	// No more events waiting.
	if (eventtail == eventhead)
	{
		return nullptr;
	}

	result = &events[eventtail];

	// Advance to the next event in the queue.
	eventtail = (eventtail + 1) % MAXEVENTS;

	return result;
}
